#!/bin/bash

: ${WOLF_CFG_FOLDER:-"config"}

XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/tmp/sockets}" \
WOLF_LOG_LEVEL="${WOLF_LOG_LEVEL:-INFO}" \
WOLF_CFG_FILE="${WOLF_CFG_FILE:-$WOLF_CFG_FOLDER/config.toml}" \
WOLF_PRIVATE_KEY_FILE="${WOLF_PRIVATE_KEY_FILE:-$WOLF_CFG_FOLDER/key.pem}" \
WOLF_PRIVATE_CERT_FILE="${WOLF_PRIVATE_CERT_FILE:-$WOLF_CFG_FOLDER/cert.pem}" \
WOLF_PULSE_IMAGE="${WOLF_PULSE_IMAGE:-ghcr.io/games-on-whales/pulseaudio:master}" \
WOLF_RENDER_NODE="${WOLF_RENDER_NODE:-/dev/dri/renderD128}" \
WOLF_STOP_CONTAINER_ON_EXIT="${WOLF_STOP_CONTAINER_ON_EXIT:-TRUE}" \
WOLF_DOCKER_SOCKET="${WOLF_DOCKER_SOCKET:-/var/run/docker.sock}" \
RUST_BACKTRACE="${RUST_BACKTRACE:-full}" \
RUST_LOG="${RUST_LOG:-WARN}" \
HOST_APPS_STATE_FOLDER="${HOST_APPS_STATE_FOLDER:-$WOLF_CFG_FOLDER}" \
GST_DEBUG="${GST_DEBUG:-2}" \
./build/src/moonlight-server/wolf