apiVersion: v1
kind: Pod
metadata:
  name: stream-base
  namespace: deskube
  labels:
    app: stream-base
spec:
  restartPolicy: OnFailure
  containers:
  - name: stream-base
    image: "registry.desku.be/deskube/streamer-base:latest"
    imagePullPolicy: Always
    # Add security context for privileged mode
    securityContext:
      privileged: true
      capabilities:
        add:
          - SYS_ADMIN
          - NET_ADMIN
    env:
    - name: RECEIVER_IP
      valueFrom:
        configMapKeyRef:
          name: stream-base-config
          key: receiver_ip
    - name: XDG_RUNTIME_DIR
      value: "/tmp/xdg-runtime-dir"
    resources:
      limits:
        cpu: "500m"
        memory: "1Gi"
      requests:
        memory: "1Gi"
        cpu: "500m"